### ISSUE TITLE
jQuery Mobile breaks without Migrate but no warning is triggered with Migrate

### ISSUE THREAD

**Issue by teo1978** [jquery/jquery-migrate#205]
With jQuery3+jQueryMobile (a custom build with only "virtual mouse events" selected), I get this fatal error:
```
jquery.mobile.custom.virtual_mouse.js:44 Uncaught TypeError: Cannot read property 'concat' of undefined(anonymous function) 
@ jquery.mobile.custom.virtual_mouse.js:44(anonymous function) 
@ jquery.mobile.custom.virtual_mouse.js:523(anonymous function) 
@ jquery.mobile.custom.virtual_mouse.js:20(anonymous function) 
@ jquery.mobile.custom.virtual_mouse.js:22
```

If I add the **Migrate** plugin, **the error goes away** and the code works, but no warning is generated that would help me find what the incompatibility is.
The only warnings I'm seeing are being triggered by jQueryUI, not jQuery Mobile.

**Comment by dmethvin** [comment]
I submitted a [PR](https://github.com/jquery/jquery-mobile/pull/8436/files) to Mobile with some suggested fixes, @arschmitz has already implemented them in master.

In the past we've just told people to upgrade to the latest Mobile/UI rather than trying to detect all the incompatibilities in the existing ones. If we give a message about this the problem would be that the issue is in Mobile and there isn't anything the user can do about it. What kind of message would you like?

**Comment by teo1978** [comment]
> If we give a message about this the problem would be that the issue is in Mobile and there isn't anything the user can do about it

That doesn't make sense. The same reasoning would apply to any of Migrate's warning, if jQueryMobile happens to use the corresponding obsolete or no-longer-supported feature.

In this particular case it's jQuery Mobile, but it could be the user's own code that one is trying to migrate. 

> What kind of message would you like?

One telling me what no-longer-supported feature the code is trying to use use. 

In this case it looks like it's something related to `$.event.props': it seems it is undefined while jQueryMobile expects it to be an array. There seems to be also an **API documentation issue** here, because neither at http://api.jquery.com/category/deprecated/ nor at http://api.jquery.com/category/events/event-object/ do I find any mention of `props` at all, neither of what it is in the first place nor of it being deprecated.

Unless jQueryMobile is using some undocumented feature, in which case it would be entirely jQueryMobile's fault and not Migrate.... no wait, if that was the case, using Migrate wouldn't prevent the error.

**Comment by dmethvin** [comment]
> What kind of message would you like?
>> One telling me what no-longer-supported feature the code is trying to use.

Right, but it isn't *your* code so having detailed explanations of jQuery Mobile's use of an undocumented internal feature isn't going to help. As the end user programmer, the information I *think* you want is, "What version of jQuery Mobile fixes this?" At the moment there is none. In another ticket you mentioned that you wanted the name of the file so you might infer where the problem is. I assume the next step for you would be to go and either report the bug or find the version that has already fixed it.

> Unless jQueryMobile is using some undocumented feature, in which case it would be entirely jQueryMobile's fault and not Migrate.... no wait, if that was the case, using Migrate wouldn't prevent the error.

The reason Migrate fixes the problem with Mobile is that it shims `$.event.props` to allow older code to work. jQuery Mobile doesn't *add to* props but does "borrow" the props list for its own use. I don't know of any other code that does that. We might be able to put in a getter for `$.event.props.concat` to give a message for this particular situation.

**Comment by teo1978** [comment]
> Right, but it isn't your code

But it could be! 
Can you please forget for a moment the fact that, in this **particular case** it is jQueryMobile that is using the obsolete features, and consider the general issue?

Migrate's job, as I understand it, is to:
- make legacy code work, which used to work with earlier versions of jQuery and would normally break with jQuery 3
- print warnings about every part of the code that would or could break (as well as parts that use obsolete feature that will stop being supported in the future)

Here it's failing to do the second part.

I happened to discover this with jQuery Mobile, but it could have been my code or, more likely, some other third-party library: and if that library it is not compatible with jQuery 3 and it is already the latest version (e.g. it's an old unmaintained but cool library), I may want to try and fix it myself, couldn't I? 


Now let's put it another way. **Consider this case**:
- I have a bunch of code: my code + jQuery 2 + other libraries (could be jQuery Mobile and/or anything else)
- I plan to migrate to jQuery 3.
- **First thing I do** is replace jQuery 2 with jQuery 3 **and** **add the Migrate plugin**, because I am not a foolish optimist
- I go through all the warnings and fix what's causing them
- I have no more warnings, so it's safe to assume that **I can remove the Migrate plugin** and all the code is going to work
- it doesn't. An error occurs of which I had not been warned about.

Be it jQueryMobile, another 3rd party library, or my own code, Migrate is just failing to do what it is supposed to do.


> jQuery Mobile doesn't add to props but does "borrow" the props list for its own use. I don't know of any other code that does that

**Is that an abuse of the API?** I mean, is jQuery Mobile using an undocumented internal feature that was never explicitly supported and they shouldn't ever have used in the first place? Because if that is the case, then you're right that the issue we are discussing is not a Migrate issue. But if that is not the case, then "_I don't know any other code that does that_" is not a relevant argument. I assume you know a huge lot of code, but I don't think it's safe to assume that you know every single piece of JavaScript code using jQuery that has ever been written in the world.

**Comment by arschmitz** [comment]
> Unless jQueryMobile is using some undocumented feature, in which case it would be entirely jQueryMobile's fault and not Migrate.... no wait, if that was the case, using Migrate wouldn't prevent the error.

Yes it's true we were. Many of the original developers of jQuery Mobile were also developers of jQuery and jQuery UI, and so were aware of many internal undocumented API's. Some of these api's were used to allow for needed features or workarounds or some times just unintentionally because they forgot it was not documented. We fix these issues as we find them like in this case. Migrate works around this issue for you because jQuery Mobile works closely with jQuery to ensure compatibility and our CI tests against the git version of jQuery so we can ensure that when a new version of jQuery is released it will be compatible with current versions of jQuery Mobile and jQuery UI ( though sometimes only through the use of migrate like here ) 

We are currently preparing the alpha release for jQuery Mobile 1.5 which will be out in next couple weeks and will fix this issue. 

I do agree with dave here that i'm not sure it makes sense to warn on something that there is nothing you can do about and is not documented so should not be an issue in user code.

**Comment by dmethvin** [comment]
Migrate isn't ever going to catch 100% of the differences from one version to another. Some of them are just too hard to detect, and others are rare or obscure enough that almost nobody encounters them. It takes real effort on someone's part (usually the core team) to add detections for all these cases without generating false positives. Sometimes after a release we determine that a problem is more common than we thought, such as #174. In those cases we do more work to detect and fix it. 

Our advice for any major jQuery core version has always been to use the latest UI and Mobile. This time there is a longer-than-typical lag between core coming out and a compatible UI/Mobile release being available, but both have 3.0-compatible code ready and expect a release soon.

I'm not trying to place blame, I am asking what message might be given by Migrate that would actually help the situation. I think it's possible to give a message for the `$.event.props.concat` bug. What should that message be? What action should the user take with that message? You don't need to continue ad infinitum to make the argument for a message, you need me to understand what message would help you.

**Comment by arschmitz** [comment]
Perhaps when migrate works around something jQuery Mobile or UI specific there should be a warning something to the effect of "Your current version of jQuery Mobile is not supported by jQuery 3.0 without the migrate plugin please check jquerymobile.com for a newer version"

**Comment by teo1978** [comment]
Ok so now it's clear that this is caused by the use of an undocumented internal feature that shouldn't ever have been used in the first place, even when it worked. So it's not a bug in Migrate as I thought it was... except that if Migrate *does* take action to prevent the errors, then it probably should also warn. Doing one but not the other leads to the inconsistent situation where you have no warning with Migrate but the code breaks without it.

>  I think it's possible to give a message for the $.event.props.concat bug. 

Well that would be awesome.

> What should that message be? 

I can't help much here since I haven't fully understood what exactly is going on under the hood. I personally would be happy with knowing who is doing what that it shouldn't do (at the highest possible level, e.g. reading `event.props` if that is the object that is not supposed to be exposed by the API), and knowing that this will (or could) break if I remove the Migrate plugin (as opposed to being just a warning about some obsolete but still working feature).

Are you sure this is specific to `concat` btw? It looks like the problem is that `props` is undefined. Actually I don't fully understand how Migrate fixes the issue; I've had a look at the source and I see it adds elements to that array *if* it exists, so I'm surprised it fixes an error caused by it being undefined. But obviously I have no idea.

> What action should the user take with that message?

They have two options: either switch back to jQuery 2.x, or keep using the Migrate plugin (as opposed to what you would normally do which is using Migrate only temporarily until you get rid of all the warnings, and then remove it).
