### ISSUE TITLE
Put the file name in the warning message so I don't need to look at the stack trace

### ISSUE THREAD

**Issue by teo1978** [jquery/jquery-migrate#210]
The name of the file where the code triggering the warning is should be part of the warning message, either at the beginning or at the end so it can easily be spotted.

Quoting dmethvin from another ticket:

> To keep the message readable and short I think it should just be the file name part, not the full URL. The docs in warnings.md should also be updated to indicate the file name is in the message.

Use case: sometimes you have warnings (elt's consider the case of warning about deprecated stuff that still works) due to third party libraries that you're never going to fix, so they make a lot of noise that you can't get rid of, while you are trying to spot the migration issues in your own code.

It's painful to have to inspect the traces one by one.

**Comment by smohadjer** [comment]
+1

**Comment by sebhaase** [comment]
+1

**Comment by chitwoodj** [comment]
Achitwood951@gmail.con
-- 
Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 3/7/2017, 3:14 PM sebhaase <notifications@github.com> wrote:

  
    
      +1

**Comment by dmethvin** [comment]
I've looked at finding the right file and do not think there is a remotely accurate way to do so. The problem is that "the file name" is several layers down the stack but the number of layers varies. The unit tests are probably the easiest cases since they only involve individual files for Migrate, jQuery, and the unit tests. It only gets more complicated with combined files, plugins, async code such as ajax, or event handlers that are called back from within jQuery. Unreliable information here would be worse than just leaving the stack trace.

If someone would like to continue experimenting with this, add the following code [after the warning message output](https://github.com/jquery/jquery-migrate/blob/dfc7de9d09a5975773715b1d46e4f199bd1ffa5d/src/migrate.js#L52):

```js
			try {
				throw 1;
			} catch ( err ) {
				console.log( err.stack );
			}
```
