### ISSUE TITLE
Being able to receive warnings in custom handlers

### ISSUE THREAD

**Issue by eirslett** [jquery/jquery-migrate#250]
An example would be when using jquery-migrate in unit tests:

`jQuery.migrateWarningHandler(warning => failTheUnitTest(warning))`

or one could throw an exception possibly.

Migrate warnings would then fail the build, so problems are discovered early.

See [This PR in jquery-ui](https://github.com/jquery/jquery-ui/pull/1774) for context.

(Ideally it would be possible to use both in 1.4.x and 3.x, since that is what jquery-ui uses)

**Comment by dmethvin** [comment]
See #15 and #296 for some approaches on this. I think they solve that use case? You can also patch `console.warn` and fail the test if you see `JQMIGRATE` in the message.

**Comment by eirslett** [comment]
I cannot find issue #296 (in the jquery-migrate project), which one is that?
Yes, one could simply monkey-patch `console.warn` or `jQuery.migrateWarnings.push`, but I'm not sure it's a good idea - it relies on undocumented internal implementation details of jquery-migrate, which could be changed at any time.

**Comment by dmethvin** [comment]
Sorry I meant #196. I don't expect we'll change those details since we've advocated their use in several tickets at this point. If you'd like to use it and add a comment to that effect please file a PR. 

Adding a handler interface is always more complicated that you might think, it needs to define what happens for multiple listeners and there's the possibility of recursion (e.g., a warning handler calling a jQuery method that itself generates a warning). Yes all of those things can be defined, guarded, or documented away but given the small number of use cases I think we have acceptable solutions already.

**Comment by eirslett** [comment]
Ok, thank you for your responses! I will try to monkey-patch `jQuery.migrateWarnings.push` then.
