### ISSUE TITLE
Test failure: "effects: jQuery.easing"

### ISSUE THREAD

**Issue by Krinkle** [jquery/jquery-migrate#255]
This has been failing for a while now.

* Last passing build was 13 February 2017 (<http://swarm.jquery.org/job/4745>).
* 20 February build (<http://swarm.jquery.org/job/4793>) has 1 failure:
  * `core: jQuery.holdReady`
* 13 March build (<http://swarm.jquery.org/job/4938>) has 2 failures:
  * `core: jQuery.holdReady`
  * `effects: jQuery.easing`
  * (jQuery 3.2.0 released.)
* 20 March build (<http://swarm.jquery.org/job/5003>) fixes holdReady, effects failure remains
  * (jQuery 3.2.1 released.) 

Commits in jquery/jquery from 13 March:
* https://github.com/jquery/jquery/commit/c920ff6e322baddbb2bd04125c5577244dcb0320 ("Dimensions: ignore transforms when retrieving width/height")
* https://github.com/jquery/jquery/commit/96533cd0e889a09ca71b90d74d71e590623cf26f ("Remove dead code")
20 Match:
* https://github.com/jquery/jquery/commit/c4598da4293afa4bb9c0425d964432e918055aa6 ("CSS: retrieve inline style before computed")

<img width="1263" alt="screen shot 2017-03-30 at 11 38 47" src="https://cloud.githubusercontent.com/assets/156867/24520479/799368fe-153d-11e7-8450-e49364412356.png">
<img width="636" alt="screen shot 2017-03-30 at 11 38 55" src="https://cloud.githubusercontent.com/assets/156867/24520480/7993cf06-153d-11e7-9bc9-5b879555ec32.png">

-------

  _See also https://github.com/jquery/jquery/issues/3583_

**Comment by Krinkle** [comment]
@dmethvin fd324d2 fixed the test in most browsers, except Edge 15. It seems the sixth assertion doesn't happen in Edge 15, causing the test to timeout.

I've already re-ran it a few times to make sure it (probably) isn't an intermittent issue.

http://swarm.jquery.org/job/5790
<img height="272" alt="screen shot" src="https://user-images.githubusercontent.com/156867/28335327-a518663c-6bc3-11e7-8ace-97d2b7117949.png">
<img width="920" alt="screen shot" src="https://user-images.githubusercontent.com/156867/28335323-a36f6f42-6bc3-11e7-851f-7f121b119ece.png">

**Comment by dmethvin** [comment]
Yeah that's strange because I ran the test locally here (Microsoft Edge 40.15063.0.0) and it worked fine. However, I updated a BUNCH of stuff to get this to work including a move to QUnit 2.0 and found a subtle unit test bug in the process. Maybe this is one of those, I'll take a look.

The strange thing is, the unit tests won't run in PhantomJS 2 for me but they do in CI. Go figure. Probably another Windows thing.

**Comment by dmethvin** [comment]
This has me really puzzled because it is running fine on my local MS Edge. I thought maybe it was the fact that we were using `expectWarning` async and changed that, but no effect on the timeout.  I can stumble around and change other things but for now I think I'll leave this as-is. At least all the other broken things are fixed. I still need to get tests running locally with PhantomJS 2 on Windows.

**Comment by Krinkle** [comment]
@dmethvin When running the jQuery Migrate tests through BrowserStack Live on the same OS/Edge version, they also pass (see the Aug 14 build at <http://swarm.jquery.org/project/jquerymigrate>).

Looks like it only fails through the BrowserStack API workers, perhaps some kind of background/focus-related issue?

**Comment by Krinkle** [comment]
I've fixed https://github.com/jquery/testswarm/issues/316. There is no error because the upload is triggered by a timeout. However, it seems part of the `inject.js` script was out of sync with the current db schema and wrongly using the "error" status code instead of the "aborted" (timeout) error code. This is now fixed.

The manual run for Edge 15 / jQuery Migrate completes in about 10 seconds.
<http://swarm.jquery.org/job/5977> / <http://swarm.jquery.org/result/2383293>

The BrowserStack worker times out after 70 seconds in QUnit test 42/43 ("42. effects: jQuery.fx.interval - no warning on animations").

So presumably whatever completes this async test, it sometimes isn't triggered for over 60 seconds in Edge 15.
<https://github.com/jquery/jquery-migrate/blob/e4a31bde56709dcc0b319a8d80043c1420a0d3ae/test/effects.js#L48-L61>

I'm guessing the animation completion depends on the browser calling `requestAnimationFrame` - which presumably isn't happening for a while. Might be that the VM doesn't have the browser window in the foreground, which might enable some kind of idle/optimisation mode in Edge, similar to Chrome. Except as far as we can tell, the Chrome VMs do have the browser window in the foreground. (I'll file a browserstack issue)

**Comment by mgol** [comment]
@Krinkle BrowserStack provides videos of all test runs. It's a little hard to locate which run represents which TestSwarm test but it's enough to log in to TestSwarm and restart a job while looking at https://www.browserstack.com/automate/.

The browser is not covered by anything but the resolution is low enough that the test iframe doesn't fit in the screen. This might be what's causing animation issues.

I'm not sure what to do about it. Even if resolution was greater, the list of test runs scheduled for this browser displays above the iframe so the iframe does go out of view eventually.

Resolving that may require changes in TestSwarm itself.

<img width="510" alt="screen shot 2017-08-21 at 11 25 11" src="https://user-images.githubusercontent.com/1758366/29512840-b7143982-8663-11e7-9e86-63c99cf407ad.png">

**Comment by Krinkle** [comment]
@mgol The manual tests I ran also used the TestSwarm runner page. I tried to reproduce it just now and I think you're right. When I did it last week, I had the window maximised in BrowserStack (as is the default) and it was just tall enough to have part of the iframe visible. When I resized the window like in your screenshot, the test started to stall until I scrolled down at which point it finished immediately.

**Comment by dmethvin** [comment]
Ugh, that explains why it works fine outside of TestSwarm. The iframe on on the TestSwarm page has focus all during the testing though, right? Maybe this is something we should ask the Edge team to change?

**Comment by mgol** [comment]
In my testing for https://github.com/jquery/jquery/pull/3151 I've discovered browsers are getting more & more aggressive at delaying computing stuff for elements out of the visible screen area. This doesn't just apply to iframes, though these optimizations cause different side effects in different browsers.

Even if the Edge team changed that here we'd still have a similar problem in many other browsers. In https://github.com/jquery/jquery/pull/3151 I even had to make sure the tests that create their own iframes are doing it at the top of the QUnit test window as otherwise they might have lost focus as well.

I think there's just no way around that (long term) than changing the TestSwarm layout to make sure the iframe is always visible and perhaps even changing our QUnit setup so that iframes created by tests appear at the top, not at the bottom. Perhaps it may even require changes in QUnit itself (cc @leobalter).

**Comment by dmethvin** [comment]
I wonder if we could just override `jQuery.fx.start/stop` in the unit tests to avoid `rAF` entirely? For the current things that Migrate does it doesn't matter whether `rAF` is in use or not. Since there isn't anything browser-specific in it either I suppose we could skip this test in Edge.

Neither solution is ideal, but having the unit tests consistently fail is worse.

**Comment by Krinkle** [comment]
> The iframe on on the TestSwarm page has focus all during the testing though, right?
> Maybe this is something we should ask the Edge team to change?

Yes, the window has focus, but it seems Edge 15 introduces an optimisation where iframes that are out-of-view iframes within a foreground window or tab, are also considered in the "background", like a tab or window that is not in the foreground.

I might still be worth reaching out to Edge 15 if this was unintentional. Also, it'd be good to verify whether Edge is emitting the proper Page Visibility API or window focus/blur events when they make this decision. As long as they're doing that, I wouldn't consider this a bug.

And yep, agreed, we should try and move the iframe to higher in the viewport. I'll see what I can do.

**Comment by mgol** [comment]
In terms of unbreaking the build ASAP I agree with @dmethvin that we can either skip a problematic test in Edge 15 via UA sniffing or mock it to skip `rAF`. My remarks were more of a general problem that will hit us from time to time and that require changes beyond jQuery or the Migrate prokect.

**Comment by Krinkle** [comment]
Per , the build is passing now :)

[<img width="1195" alt="screen shot 2017-08-23 at 20 31 00" src="https://user-images.githubusercontent.com/156867/29634511-0a86b132-8842-11e7-90ee-0855a882841e.png">](http://swarm.jquery.org/project/jquerymigrate)

**Comment by dmethvin** [comment]
YAY! 🎉
