### ISSUE TITLE
The `then` method on the `Deferred` object is executed asynchronously

### ISSUE THREAD

**Issue by prantlf** [jquery/jquery-migrate#286]
Executing the following code:

```js
var deferred = new jQuery.Deferred();
deferred.then(function () {
  console.log('done');
});
deferred.resolve();
console.log('resolved');
```
in jQuery 2.x writes:

```
done
resolved
```

while in jQuery 3.x it is:

```
resolved
done
```

Reliably reproducing and debugging asynchronous problems like this is not easy. It is probably impossible to log a warning about this king of problem. But it would be possible possible to use the jQuery Migrate plugin to run the application in a "compatibility synchronous mode" and compare the results with running the application in the "asynchronous mode". For example:

```js
// jQuery Migrate will replace `then` in `Deferred` with a synchronous
// implementation, if this property is se to true in the client code
jQuery.synchronousDeferred = true;
```

Similar compatibility problem could occur with the error catching and converting the error to promise rejection.

Would you consider adding such compatibility mode for the Deferred object?

**Comment by dmethvin** [comment]
This was documented in the upgrade guide.
https://jquery.com/upgrade-guide/3.0/#breaking-change-and-feature-jquery-deferred-is-now-promises-a-compatible

I agree it's probably impossible to warn about this in Migrate, we considered ways to do it without throwing a bunch of spurious and incorrect warnings. In a quick search of code it seemed like most uses were not affected by the change, and of course this is a desired change by people who want consistent Promise/A+ behavior in older browsers like IE11. Those who don't can change `.then()` to `.done().fail()` and get the old behavior, even in 3.x.

The main goal of Migrate is to detect problems and give enough information to allow a developer to fix them in their code. It's not meant as a a long-term crutch so that something written for jQuery 1.3.2 can continue to run on jQuery 3.2.1 without changes. That is exactly why Migrate 3.x doesn't try to fill everything that was removed, you should [deal with that](https://blog.jquery.com/2016/05/19/jquery-migrate-1-4-1-released-and-the-path-to-jquery-3-0/) before trying to upgrade to jQuery 3.x. If you "can't" do that then stay with jQuery 2.x until dependencies are compatible with 3.x.

There are currently no configuration flags in Migrate. In a mixed-code environment where plugins from different sources expect different jQuery versions, there is no flag that can provide the legacy behavior that each plugin expects. If you need behavior from a specific older version of jQuery then by all means use that version and don't upgrade jQuery. If you have control over the code, either because it's yours or you can submit a PR, then upgrade it to work with the later version of jQuery. 

Does that make sense?

**Comment by prantlf** [comment]
Yes, it makes sense. I didn't mean to use Migrate on a long-term. But being able to run it for a couple of week without being afraid, that the application is likely to crash would help :-)

Your answers for #284 and #285 helped me realise, that Migrate is a tool to help the developer fix upgrade issues, but not all of them to restore the previous functionality, which would be probably a huge effort. Am I right? Your statement from your previous answer leads me to it:

> Migrate 3.x doesn't try to fill everything that was removed

**Comment by dmethvin** [comment]
> Migrate is a tool to help the developer fix upgrade issues, but not all of them to restore the previous functionality

Where it doesn't generate false alarms and doesn't require crazy workarounds, we try to restore the old behavior in Migrate. That's usually easy with something like a removed API where we just put the removed code in Migrate.

It's not always possible to restore the old functionality because its behavior conflicts with the new functionality. (`jQuery.Deferred`s are an example.) If you have some jQuery 3.0 code that expects the new behavior, and some older plugin that was written for jQuery 2.0 that expects the old behavior, one of them is going to break. You might be able to "fix" it by including two versions of jQuery via `jQuery.noConflict()` but that's not a good solution. A compat flag in Migrate wouldn't solve it either and would just make things more confusing.

**Comment by prantlf** [comment]
Understood. Thank you for your answers!
