### ISSUE TITLE
The UMD code fragment does not call AMD's define correctly

### ISSUE THREAD

**Issue by lddubeau** [jquery/jquery-migrate#287]
The call currently is like [this](https://github.com/jquery/jquery-migrate/blob/1cb2093f4abd5cef29de645875dd397b7521798c/src/intro.js#L5):

    define( [ "jquery" ], window, factory );

AMD does not define semantics for the call pattern above. RequireJS happens to ignore the 3rd argument and treats it as `define(["jquery"], window)`. Thus it defines the module to have for value `window`. This makes loading the plugin through RequireJS ---  and most likely any AMD loader --- a complete non-starter. I've not checked what SystemJS would do with it, but it is unlikely that it would interpret it as it is meant to be interpreted. I'm wondering whether the problems reported in #272 and #273 are caused by this incorrect `define` call. Since a `define` call with the pattern above has no defined semantics, tools that aim to process AMD `define` may just crash.

It should be something like the following:

    define( [ "jquery" ], function ($) {
        return factory($, window);
    });

When I make the replacement manually in my local installation of `jquery-migrate`, it becomes usable.

**Comment by mebibou** [comment]
Is there any alternative way to import the plugin when using webpack then? this is pretty much a no-goer

**Comment by dmethvin** [comment]
@mebibou thanks for making a comment, somehow I had missed the issue being opened. 

@lddubeau I agree it doesn't look right. Would you like to submit a pull request? The reason it didn't get caught was because the original PR lacked a unit test. It's a bit difficult to test this, although I think it could be done in an iframe test which we do have the ability for, see the existing unit tests for some examples. If that's too much work, I would be glad to create the unit test if you can provide a standalone example proving that the PR works.
