### ISSUE TITLE
Incorrect warning for use of jQuery.fx.interval

### ISSUE THREAD

**Issue by daviesian** [jquery/jquery-migrate#292]
Following on from #276 - I had the same problem and managed to catch it in the act. In particular, jQuery 3.2.1 does still reference `jQuery.fx.interval` in one place:

https://github.com/jquery/jquery/blob/3d732cca6b5076a9d13eee98e2b075b37384cd91/src/effects.js#L37

It appears that this is intentional, and will just resolve to `13` in normal usage. However, with jquery-migrate loaded, that line causes a deprecation warning to be incorrectly printed.

One could argue that this should only happen on particularly old browsers, but the `if` statement above also causes the `setTimeout` path to run when the document is hidden (if the browser is minimised, for instance). This seems like a perfectly legitimate use-case.

It's not entirely clear whether this is a bug in jQuery (where `jQuery.fx.interval` claims to have been deprecated) or in jquery-migrate (where the warning is being printed despite the fact that the usage is in core jQuery code). I'd be happy to work on a pull request for whichever people think is the culprit.

**Comment by dmethvin** [comment]
Yeah, I agree the `document.hidden` case creates a strange situation here, and since that case will be around even after non-`rAF` browsers die it seems like a bad idea to give a warning for it. Perhaps we should only warn on this property being set, although that won't catch cases where third-party code uses it as a timeout number. We could just switch the internal usage to a hard-coded number, it's only there to prevent things backing up in the animation queue.

**Comment by dmethvin** [comment]
Alternatively I suppose we could check for `document.hidden`?

**Comment by daviesian** [comment]
This isn't my code, of course, but it seems to me that if jQuery claims `jQuery.fx.interval` is deprecated then it probably shouldn't continue to use it internally. And checking for `document.hidden` in jquery-migrate would potentially suppress correct warnings for some strange use-cases. 

As far as I can tell, this is literally the only reference to `jQuery.fx.interval` in the whole jQuery codebase, apart from a couple of unit tests. My vote (for what it's worth) would be to replace the internal usage with a hard-coded number! Would you like me to submit a patch?

**Comment by mgol** [comment]
> This isn't my code, of course, but it seems to me that if jQuery claims jQuery.fx.interval is deprecated then it probably shouldn't continue to use it internally.

It's deprecated because it doesn't always have effect (e.g. when the browser supports `requestAnimationFrame`) and we don't want people to change it and to rely on it for their own timeouts. That said, for backwards compatibility we still take the setting into account (though it's debatable how important that is - we can certainly discuss that) as long as we define this property.

**Comment by daviesian** [comment]
That makes sense. I shall leave this with you guys who actually understand the intricacies of the code!

**Comment by dmethvin** [comment]
Thank you for pointing out the problem! It looks like what happened is that the Migrate code was added and later we fixed jQuery animations by falling back to `setTimeout` when the window is hidden.

**Comment by daviesian** [comment]
Thanks so much folks!
