### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by kesselaprod** [jquery/jquery-migrate#329]
So I recently installed jQuery Migrate 3.1.0 from [this ](https://code.jquery.com/jquery/) source into a WebsiteBaker CMS.

This is what the console reads now:
`Uncaught TypeError: Cannot read property 'prototype' of undefined
    at jquery-migrate-min.js:404
    at jquery-migrate-min.js:20
    at jquery-migrate-min.js:22`

![jquery migrate](https://user-images.githubusercontent.com/34941707/77524343-78876180-6e87-11ea-9ac9-61b461d9c806.png)

How do I fix this?

**Comment by mgol** [comment]
Thanks for the report but this doesn't tell us much without a test case. Please provide one at https://jsbin.com

Also, what jQuery versions do you use with Migrate?

**Comment by kesselaprod** [comment]
> Thanks for the report but this doesn't tell us much without a test case. Please provide one at https://jsbin.com
> 
> Also, what jQuery versions do you use with Migrate?

I'm using jQuery Core 3.4.1.

How I am supposed to provide a test case if the only thing I did was to install the plugin into an embbed system?

**Comment by mgol** [comment]
It's just that we do test Migrate against jQuery Core releases so we know it works. When you just provide an error message of an immediate crash it's quite likely something's incorrect in how you load the files and the only thing we can do without a test case is guessing. Preparing a test case would require you to experiment with the code around the error.

I'll propose you to try different things in the project as I can't do it myself, maybe that will help.

First of all, please load the unminified copies of both jQuery & jQuery Migrate instead of the minified ones, error messages should be more readable there, pointing to the error more precisely.

Secondly, can you make sure they are loaded in a proper order?

Once that's done, I can have a look at the line where you see the error. No promises, though, sometimes it's hard to debug the issue without a test case.

**Comment by kesselaprod** [comment]
> It's just that we do test Migrate against jQuery Core releases so we know it works. When you just provide an error message of an immediate crash it's quite likely something's incorrect in how you load the files and the only thing we can do without a test case is guessing. Preparing a test case would require you to experiment with the code around the error.
> 
> I'll propose you to try different things in the project as I can't do it myself, maybe that will help.
> 
> First of all, please load the unminified copies of both jQuery & jQuery Migrate instead of the minified ones, error messages should be more readable there, pointing to the error more precisely.
> 
> Secondly, can you make sure they are loaded in a proper order?
> 
> Once that's done, I can have a look at the line where you see the error. No promises, though, sometimes it's hard to debug the issue without a test case.

At first thank you for reply. I understand your situation but the only clue on how to tackle this problem is if I a clean installation of the backend

**Comment by dmethvin** [comment]
It's been more than 2 weeks, we can reopen this ticket if additional information warrants.

**Comment by lukeliasi** [comment]
I got this error when I was using jquery slim https://jsbin.com/jurusunaza/1/edit?html,console when changing to normal jquery version error goes away.

**Comment by mgol** [comment]
@lukeliasi Oh, that's true, Migrate doesn't support the jQuery slim build right now. It totally should! I submitted an issue: #345.

**Comment by mgol** [comment]
@lukeliasi The issue linked above is now fixed, Migrate 3.3.0 will support jQuery slim builds.
