### ISSUE TITLE
does jQuery Migrate expose back fixed vulnerabilities?

### ISSUE THREAD

**Issue by almotos** [jquery/jquery-migrate#368]
I will try to ask this simple:

let's say I use jQuery 2.2.4 (which has XYZ vulnerabilities) then I migrate to 3.4.1 (which fixes XYZ vulnerabilities). As a side result, my code starts failing because of the breaking changes, then I use jQuery Migrate to fix these breaking changes.

Do the use of jQuery Migrate bring back X or Y or Z or all vulnerabilities back?

The oficial documentation is not clear about this.

**Comment by mgol** [comment]
I'm not sure about Migrate 1.4.1, @dmethvin would know more about that. However, Migrate 1.x is meant for jQuery 1.x or 2.x which have some vulnerabilities anyway.

As for Migrate 3.x, by default it shouldn't bring back any vulnerability. However, if you call `jQuery.UNSAFE_restoreLegacyHtmlPrefilter()` as described by the [jQuery 3.5 upgrade guide](https://jquery.com/upgrade-guide/3.5/), you will bring back the vulnerability that was fixed in jQuery 3.5.

**Comment by mgol** [comment]
Closing as answered.
