### ISSUE TITLE
"migrateWarnFunc( jQuery, "isArray", Array.isArray" should be under "if ( jQueryVersionSince( "3.2.0" ) )" condition

### ISSUE THREAD

**Issue by ildar-aim** [jquery/jquery-migrate#370]
as it has been deprecated since 3.2.0
https://api.jquery.com/jQuery.isArray/

currently, it is in the  
```
if ( jQueryVersionSince( "3.3.0" ) ) {
...
}
```
block

**Comment by mgol** [comment]
Nice catch! Would you like to submit a PR?

**Comment by ildar-aim** [comment]
Another issue is

```
if ( jQueryVersionSince( "3.1.1" ) ) {
    migrateWarnFunc( jQuery, "trim", function( text ) {
        return text == null ?
            "" :
            ( text + "" ).replace( rtrim, "" );
    },
    "jQuery.trim is deprecated; use String.prototype.trim" );
}
```

though 

https://api.jquery.com/jQuery.trim/
version deprecated: 3.5

Btw
Why don't you use the official replacement here (String.prototype.trim)?
_Note: This API has been deprecated in jQuery 3.5; please use the native String.prototype.trim method instead._


> Nice catch! Would you like to submit a PR?

Let's discuss all the points.

**Comment by mgol** [comment]
In general, Migrate can warn against APIs that were deprecated in later jQuery versions, the major reason why that's not always done is that jQuery often has internal usage of such APIs before they are deprecated. `jQuery.trim` is not used internally since jQuery 3.1.1 so that `if` is correct.

We don't use the native API as jQuery 3 - and also as a result Migrate 3 - support Android Browser where native `trim` is broken. See https://github.com/jquery/jquery/blob/3.5.1/src/deprecated.js#L16-L18.

**Comment by ildar-aim** [comment]
PR
https://github.com/jquery/jquery-migrate/pull/373

**Comment by ildar-aim** [comment]
Sorry guys.

It seems there were two GitHub accounts that is why CLA didn't work.

I tried the article 
https://docs.github.com/en/github/using-git/changing-author-info which completely ruined the PR

I have created a new fork and a new PR

**Comment by ildar-aim** [comment]
https://github.com/jquery/jquery-migrate/pull/375
