### ISSUE TITLE
Detect and warn about Ajax JSON requests promoted to JSONP

### ISSUE THREAD

**Issue by dmethvin** [jquery/jquery-migrate#372]
https://github.com/jquery/jquery/pull/4754

Since this is a security-related issue I suspect we won't want to fill it.

**Comment by mgol** [comment]
What do you mean by "fill it"?

**Comment by dmethvin** [comment]
Put the functionality back so it continues to work the same way it does now.

**Comment by mgol** [comment]
Yeah, I don't think we want to do that here.

Now, that brings me back to the question of what's the goal of Migrate 3.x. Do we want it to work with jQuery 4 as well or will that one have Migrate 4.x? Because if that's the case then we shouldn't really polyfill any deprecated APIs in Core 3.x but only warn since they're all in source.

**Comment by dmethvin** [comment]
I would like to avoid another jump like we had with Migrate 1.x where users have to use two (or three!) versions of the Migrate plugin to get to the latest jQuery. Some of the changes in jQuery 1.x made it very difficult to make a single Migrate for everything. I think Migrate 3.x should work with jQuery 4.x.

**Comment by mgol** [comment]
I see, makes sense. Too bad we left some of jQuery 1.x/2.x stuff in Migrate 3.x, they'll need to stay longer.

For the sake of this issue, though, I agree, let's not bring back potential security issues, a warning should be fine. Especially that in most cases it should be easy to fix: just change `json` to `jsonp` explicitly.

**Comment by mgol** [comment]
PR: #376
