### ISSUE TITLE
Future of jQuery Migrate Plugin?

### ISSUE THREAD

**Issue by Deem97** [jquery/jquery-migrate#430]
1) I would like to know future of the migrate plugin, will they release migrate plugins for future jQuery version?
2) What are the drawbacks of using jQuery Migrate Plugin?

I'm asking these question here, because I can't post on forum and can't find clear answers on web.

**Comment by mgol** [comment]
Hey!

1. We have no plans to discontinue the jQuery Migrate plugin. We're going to release a major version update from time to time and then it helps to update your code so that it works with the newest jQuery version.
2. Some of the drawbacks are:
   1. It's larger than just pure jQuery.
   2. It's not tested as thoroughly as jQuery alone.
   3. You may experience lower performance in some cases, this is not the biggest focus for Migrate.
   4. One day you'll need to update it to work with a newer jQuery version and then you won't be able to rely on the behaviors it restores. It's better to prepare earlier & to not load Migrate for extended periods of time.

**Comment by Deem97** [comment]
I'm using jQuery 1.x in my project (1.11.1) and I want to upgrade it to the latest version 3.x. As for now I used it in this way.

- jquery-3.6.0.js
- jquery-migrate-1.4.1.js
- jquery-migrate-3.3.2.js 

I'm relying on the migrate plugin and have not updated the code. Because my code depends on many libraries. So is it okay to use them like that in the long run and expect that there will be another migrator plugin when jquery version 4.x comes. Can I use that migrator along with these migrators?
