### ISSUE TITLE
Fill in & warn against using push, sort & splice on jQuery objects

### ISSUE THREAD

**Issue by mgol** [jquery/jquery-migrate#473]
Those methods were removed in https://github.com/jquery/jquery/pull/4473. They were not public API but I expect there may be a lot of usage in the wild, e.g. AngularJS uses those methods on jQuery objects.

We should fill them in & warn against the usage.

**Comment by BackuPs** [comment]
I just tested jquery 4.0 and instantly ran into 5 plugins that stopped working because of this. 

Imho these undocumented Api's are more widely used then i think the jQuery Developers realise.  Removing api's functionality because they are not documented without informing and warning does not seem to be a good idea.  

I am totally support the idea, although "it is not documented",  to create a deprecation path in order to avoid websites stop working.

Thank you.

**Comment by mgol** [comment]
These APIs will be backfilled by jQuery Migrate prior to the jQuery 4.0.0 final release, so you'll be able to continue using them for as long as you need to get rid of them all. We'll also keep jQuery 3.x secure for some time after the 4.0.0 final release, possibly even for a few years.

**Comment by mgol** [comment]
PR: #529
