### ISSUE TITLE
$.browser.msie not working in jquery version v2.0.3. I am using jquery-migrate plugin also

### ISSUE THREAD

**Issue by vishnuk07** [jquery/jquery-migrate#82]
Hi,
Iam using jquery version v2.0.3
and Migrate version using v1.2.1 and checking the v1.2.2-pre also but $.browser.msie not working in both migrated versions
Any one please help me!

**Comment by mzgol** [comment]
What **exactly** do you mean by "not working"? A test case on jsBin would be best.

**Comment by dmethvin** [comment]
If you mean that in IE11 that `$.browser.msie` is not `true` that would be correct. Like most ill-advised browser sniffing, this was used to imply various features and bugs in older versions of IE that are not present in IE11. 

Also, this API returns the same values as the last version of jQuery that contained `$.browser`. We are not changing API behavior in this plugin because it is intended as a migration aid and not a long-term solution for bad code.

**Comment by vishnuk07** [comment]
Thank u dmethvin. I am checking the ie 11 version, thanks for your answer
