### ISSUE TITLE
$.sub doesn't work with jquery 1.11

### ISSUE THREAD

**Issue by eithed** [jquery/jquery-migrate#84]
Hello,

Following the upgrade from 1.10 to 1.11 $.sub fails to work properly. You can observe this issue here:

http://jsfiddle.net/07va5veg/ - correct behaviour with 1.10 - *b* function is successfully set on instance **a** of jquery and is used down the chain

http://jsfiddle.net/07va5veg/2/ - incorrect behaviour with 1.11 - while *b* function is successfully set on instance **a** of jquery, it appears that calls down the chain target original jquery object

**Comment by dmethvin** [comment]
Looks like the break happened in https://github.com/jquery/jquery/commit/825ac3773694e0cd23ee74895fd5aeb535b27da4 (master) and https://github.com/jquery/jquery/commit/2f627494f28c08e5bba3c32d6c9d9167503322fc (compat) when `rootjQuery` was removed. We should put a note there that it's required for Migrate to support `jQuery.sub`, since the jQuery codebase itself doesn't use it. And, we need a unit test in Migrate to ensure that it won't regress, I will do a patch for that. /cc @timmywil

**Comment by timmywil** [comment]
Ah yea, seems I removed it from the parameter list. In order to make this work again and keep core/init as it's own module, I think we'd use the rootjQuery in core/init if one is not defined in the parameters.

**Comment by timmywil** [comment]
A patch for this should be possible now.

**Comment by dmethvin** [comment]
This was added back and is is present in both 1.12.0 and 2.2.0. it's a bit tricky to add a unit test since I know it's going to fail for 1.11.x/2.1.x and we test on a wide range of versions. I suppose we could use `QUnit.skip` based on the jQuery version. Patches welcome here!

**Comment by dmethvin** [comment]
So, this does work with jQuery 1.12.0 and Migrate 1.3.0, although it generates a bunch of spurious warnings due to `$.sub` copying over properties to the subclass. I'm gonna declare this to be okay, although if someone wants to submit a PR to fix it that would be great.
