### ISSUE TITLE
Dashes in .data() names behavior change

### ISSUE THREAD

**Issue by dmethvin** [jquery/jquery-migrate#87]
We're using camelCase for data names where possible, and only use the dash-name if it exists in the object already. Ideally, API callers should use camelCase for accessing data names rather than dashes. If the caller gets the raw data object they'll see camelCase if they put in dash-name via the API. (Clearly this will need a longer explanation somewhere.)

https://github.com/jquery/jquery/issues/1751
https://github.com/jquery/jquery/issues/2257

**Comment by dmethvin** [comment]
API docs need some variant of this description: https://github.com/jquery/jquery/issues/1751#issuecomment-67721150

**Comment by dmethvin** [comment]
At this point I'm not sure how to make a non-noisy warning about this. It might just have to be a documentation change.

**Comment by gibson042** [comment]
I think this can be done: http://jsfiddle.net/aq992xxb/

The following cases will need warnings:
* Dashed key in a bulk setter (`$el.data({ "dashed-key": … })` does not camelCase before 3.0)
* Dashed key getter when an exact match key exists in the data object (`$el.data()["dashed-key"] = …; $el.data("dashed-key")` retrieves the exact match instead of the camelCase before 3.0)
* Update dashed key when an exact match key exists in the data object (`$el.data()["dashed-key"] = …; $el.data("dashed-key", newValue)` updates both values instead of just the camelCased one in 2.x)

**Comment by dmethvin** [comment]
We're only talking about breaking changes with regard to migration though. So we only want to give a warning if some old code no longer works. Merely using dashed keys needs to be silent unless mixed with direct data object access where the new representation would be visible?

**Comment by gibson042** [comment]
Pretty much, yeah. Access is backwards- incompatible only when the data object includes a dashed key, and _that_ can only happen through a bulk setter call (which itself is one of those warning cases) or direct manipulation.

**Comment by dmethvin** [comment]
@gibson042 How does this sound? In a call to `.data("some-name")` the 3.0 behavior is to only look for `someName` in the data item, even if `some-name` is set. Migrate can do the probe for `some-name` and see if it is present in the data object, then return that value instead of `someName` and warn about it. That's the only case I see that's easy to detect.
